export const mockData = {
  weather_information: {
    loading: false,
    currentWeather: {
      coord: {
        lon: 77.2219,
        lat: 28.6517,
      },
      weather: [
        {
          id: 721,
          main: 'Haze',
          description: 'haze',
          icon: '50d',
        },
      ],
      base: 'stations',
      main: {
        temp: 313.79,
        feels_like: 312.8,
        temp_min: 313.79,
        temp_max: 314.21,
        pressure: 1000,
        humidity: 18,
      },
      visibility: 5000,
      wind: {
        speed: 4.12,
        deg: 300,
        gust: 9.26,
      },
      clouds: {
        all: 20,
      },
      dt: 1717762479,
      sys: {
        type: 2,
        id: 145989,
        country: 'IN',
        sunrise: 1717717972,
        sunset: 1717768044,
      },
      timezone: 19800,
      id: 1273294,
      name: 'Delhi',
      cod: 200,
    },
    forecastWeather: {
      cod: '200',
      message: 0,
      cnt: 40,
      list: [
        {
          dt: 1717772400,
          main: {
            temp: 313.29,
            feels_like: 312.13,
            temp_min: 312.3,
            temp_max: 313.29,
            pressure: 999,
            sea_level: 999,
            grnd_level: 975,
            humidity: 18,
            temp_kf: 0.99,
          },
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02n',
            },
          ],
          clouds: {
            all: 17,
          },
          wind: {
            speed: 3.38,
            deg: 303,
            gust: 7.7,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-07 15:00:00',
        },
        {
          dt: 1717783200,
          main: {
            temp: 311.83,
            feels_like: 310.71,
            temp_min: 310.85,
            temp_max: 311.83,
            pressure: 999,
            sea_level: 999,
            grnd_level: 976,
            humidity: 20,
            temp_kf: 0.98,
          },
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02n',
            },
          ],
          clouds: {
            all: 14,
          },
          wind: {
            speed: 5.15,
            deg: 243,
            gust: 9.12,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-07 18:00:00',
        },
        {
          dt: 1717794000,
          main: {
            temp: 309.06,
            feels_like: 307.54,
            temp_min: 309.06,
            temp_max: 309.06,
            pressure: 998,
            sea_level: 998,
            grnd_level: 975,
            humidity: 22,
            temp_kf: 0,
          },
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          clouds: {
            all: 87,
          },
          wind: {
            speed: 5.16,
            deg: 277,
            gust: 11.07,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-07 21:00:00',
        },
        {
          dt: 1717804800,
          main: {
            temp: 308.21,
            feels_like: 306.39,
            temp_min: 308.21,
            temp_max: 308.21,
            pressure: 999,
            sea_level: 999,
            grnd_level: 975,
            humidity: 21,
            temp_kf: 0,
          },
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 85,
          },
          wind: {
            speed: 3.67,
            deg: 306,
            gust: 8.92,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-08 00:00:00',
        },
        {
          dt: 1717815600,
          main: {
            temp: 310.26,
            feels_like: 308.87,
            temp_min: 310.26,
            temp_max: 310.26,
            pressure: 1001,
            sea_level: 1001,
            grnd_level: 977,
            humidity: 21,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 70,
          },
          wind: {
            speed: 4.99,
            deg: 291,
            gust: 6.71,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-08 03:00:00',
        },
        {
          dt: 1717826400,
          main: {
            temp: 315.17,
            feels_like: 313.64,
            temp_min: 315.17,
            temp_max: 315.17,
            pressure: 1000,
            sea_level: 1000,
            grnd_level: 977,
            humidity: 15,
            temp_kf: 0,
          },
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03d',
            },
          ],
          clouds: {
            all: 40,
          },
          wind: {
            speed: 5.52,
            deg: 305,
            gust: 6.26,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-08 06:00:00',
        },
        {
          dt: 1717837200,
          main: {
            temp: 317.33,
            feels_like: 314.78,
            temp_min: 317.33,
            temp_max: 317.33,
            pressure: 997,
            sea_level: 997,
            grnd_level: 974,
            humidity: 11,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 2,
          },
          wind: {
            speed: 4.72,
            deg: 300,
            gust: 7.19,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-08 09:00:00',
        },
        {
          dt: 1717848000,
          main: {
            temp: 317.08,
            feels_like: 314.13,
            temp_min: 317.08,
            temp_max: 317.08,
            pressure: 995,
            sea_level: 995,
            grnd_level: 971,
            humidity: 10,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 3,
          },
          wind: {
            speed: 5.65,
            deg: 324,
            gust: 6.12,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-08 12:00:00',
        },
        {
          dt: 1717858800,
          main: {
            temp: 313.56,
            feels_like: 311.65,
            temp_min: 313.56,
            temp_max: 313.56,
            pressure: 997,
            sea_level: 997,
            grnd_level: 974,
            humidity: 15,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04n',
            },
          ],
          clouds: {
            all: 56,
          },
          wind: {
            speed: 6.28,
            deg: 268,
            gust: 9.08,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-08 15:00:00',
        },
        {
          dt: 1717869600,
          main: {
            temp: 309.27,
            feels_like: 308.17,
            temp_min: 309.27,
            temp_max: 309.27,
            pressure: 998,
            sea_level: 998,
            grnd_level: 975,
            humidity: 24,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04n',
            },
          ],
          clouds: {
            all: 74,
          },
          wind: {
            speed: 5.58,
            deg: 304,
            gust: 11.19,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-08 18:00:00',
        },
        {
          dt: 1717880400,
          main: {
            temp: 308.65,
            feels_like: 307.54,
            temp_min: 308.65,
            temp_max: 308.65,
            pressure: 998,
            sea_level: 998,
            grnd_level: 974,
            humidity: 25,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04n',
            },
          ],
          clouds: {
            all: 71,
          },
          wind: {
            speed: 4.96,
            deg: 284,
            gust: 11.36,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-08 21:00:00',
        },
        {
          dt: 1717891200,
          main: {
            temp: 307.18,
            feels_like: 305.84,
            temp_min: 307.18,
            temp_max: 307.18,
            pressure: 999,
            sea_level: 999,
            grnd_level: 975,
            humidity: 26,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 53,
          },
          wind: {
            speed: 5.2,
            deg: 301,
            gust: 12.02,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-09 00:00:00',
        },
        {
          dt: 1717902000,
          main: {
            temp: 309.52,
            feels_like: 308.5,
            temp_min: 309.52,
            temp_max: 309.52,
            pressure: 1001,
            sea_level: 1001,
            grnd_level: 977,
            humidity: 24,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 4,
          },
          wind: {
            speed: 5.05,
            deg: 303,
            gust: 7.66,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-09 03:00:00',
        },
        {
          dt: 1717912800,
          main: {
            temp: 315.31,
            feels_like: 312.86,
            temp_min: 315.31,
            temp_max: 315.31,
            pressure: 1000,
            sea_level: 1000,
            grnd_level: 976,
            humidity: 12,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 5,
          },
          wind: {
            speed: 4.05,
            deg: 294,
            gust: 4.47,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-09 06:00:00',
        },
        {
          dt: 1717923600,
          main: {
            temp: 317.71,
            feels_like: 314.8,
            temp_min: 317.71,
            temp_max: 317.71,
            pressure: 997,
            sea_level: 997,
            grnd_level: 974,
            humidity: 10,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 0,
          },
          wind: {
            speed: 4.48,
            deg: 278,
            gust: 5.8,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-09 09:00:00',
        },
        {
          dt: 1717934400,
          main: {
            temp: 317.38,
            feels_like: 314.84,
            temp_min: 317.38,
            temp_max: 317.38,
            pressure: 995,
            sea_level: 995,
            grnd_level: 972,
            humidity: 11,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 1,
          },
          wind: {
            speed: 5.93,
            deg: 286,
            gust: 5.87,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-09 12:00:00',
        },
        {
          dt: 1717945200,
          main: {
            temp: 314.8,
            feels_like: 312.57,
            temp_min: 314.8,
            temp_max: 314.8,
            pressure: 997,
            sea_level: 997,
            grnd_level: 974,
            humidity: 13,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01n',
            },
          ],
          clouds: {
            all: 7,
          },
          wind: {
            speed: 4.81,
            deg: 276,
            gust: 6.87,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-09 15:00:00',
        },
        {
          dt: 1717956000,
          main: {
            temp: 312.27,
            feels_like: 310.8,
            temp_min: 312.27,
            temp_max: 312.27,
            pressure: 999,
            sea_level: 999,
            grnd_level: 975,
            humidity: 18,
            temp_kf: 0,
          },
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03n',
            },
          ],
          clouds: {
            all: 31,
          },
          wind: {
            speed: 4.89,
            deg: 280,
            gust: 9.87,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-09 18:00:00',
        },
        {
          dt: 1717966800,
          main: {
            temp: 310.29,
            feels_like: 308.72,
            temp_min: 310.29,
            temp_max: 310.29,
            pressure: 998,
            sea_level: 998,
            grnd_level: 974,
            humidity: 20,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04n',
            },
          ],
          clouds: {
            all: 75,
          },
          wind: {
            speed: 5.56,
            deg: 274,
            gust: 11.68,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-09 21:00:00',
        },
        {
          dt: 1717977600,
          main: {
            temp: 308.25,
            feels_like: 307.56,
            temp_min: 308.25,
            temp_max: 308.25,
            pressure: 999,
            sea_level: 999,
            grnd_level: 975,
            humidity: 28,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 56,
          },
          wind: {
            speed: 5.09,
            deg: 270,
            gust: 11.95,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-10 00:00:00',
        },
        {
          dt: 1717988400,
          main: {
            temp: 311.33,
            feels_like: 310.28,
            temp_min: 311.33,
            temp_max: 311.33,
            pressure: 1000,
            sea_level: 1000,
            grnd_level: 976,
            humidity: 21,
            temp_kf: 0,
          },
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          clouds: {
            all: 12,
          },
          wind: {
            speed: 5.66,
            deg: 283,
            gust: 8.96,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-10 03:00:00',
        },
        {
          dt: 1717999200,
          main: {
            temp: 315.95,
            feels_like: 313.92,
            temp_min: 315.95,
            temp_max: 315.95,
            pressure: 999,
            sea_level: 999,
            grnd_level: 976,
            humidity: 13,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 56,
          },
          wind: {
            speed: 5.51,
            deg: 288,
            gust: 5.25,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-10 06:00:00',
        },
        {
          dt: 1718010000,
          main: {
            temp: 318.01,
            feels_like: 315.12,
            temp_min: 318.01,
            temp_max: 318.01,
            pressure: 996,
            sea_level: 996,
            grnd_level: 973,
            humidity: 10,
            temp_kf: 0,
          },
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 100,
          },
          wind: {
            speed: 4.32,
            deg: 260,
            gust: 5.92,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-10 09:00:00',
        },
        {
          dt: 1718020800,
          main: {
            temp: 317.99,
            feels_like: 315.1,
            temp_min: 317.99,
            temp_max: 317.99,
            pressure: 995,
            sea_level: 995,
            grnd_level: 972,
            humidity: 10,
            temp_kf: 0,
          },
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 97,
          },
          wind: {
            speed: 5.33,
            deg: 272,
            gust: 6.12,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-10 12:00:00',
        },
        {
          dt: 1718031600,
          main: {
            temp: 315.97,
            feels_like: 313.28,
            temp_min: 315.97,
            temp_max: 315.97,
            pressure: 996,
            sea_level: 996,
            grnd_level: 973,
            humidity: 11,
            temp_kf: 0,
          },
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          clouds: {
            all: 93,
          },
          wind: {
            speed: 5.24,
            deg: 271,
            gust: 7.84,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-10 15:00:00',
        },
        {
          dt: 1718042400,
          main: {
            temp: 313.9,
            feels_like: 311.8,
            temp_min: 313.9,
            temp_max: 313.9,
            pressure: 997,
            sea_level: 997,
            grnd_level: 973,
            humidity: 14,
            temp_kf: 0,
          },
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          clouds: {
            all: 95,
          },
          wind: {
            speed: 6.62,
            deg: 269,
            gust: 11.95,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-10 18:00:00',
        },
        {
          dt: 1718053200,
          main: {
            temp: 311.11,
            feels_like: 310.22,
            temp_min: 311.11,
            temp_max: 311.11,
            pressure: 997,
            sea_level: 997,
            grnd_level: 973,
            humidity: 22,
            temp_kf: 0,
          },
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          clouds: {
            all: 90,
          },
          wind: {
            speed: 7.42,
            deg: 278,
            gust: 13.87,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-10 21:00:00',
        },
        {
          dt: 1718064000,
          main: {
            temp: 309.71,
            feels_like: 308.75,
            temp_min: 309.71,
            temp_max: 309.71,
            pressure: 998,
            sea_level: 998,
            grnd_level: 974,
            humidity: 24,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 81,
          },
          wind: {
            speed: 6.85,
            deg: 281,
            gust: 14.39,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-11 00:00:00',
        },
        {
          dt: 1718074800,
          main: {
            temp: 311.59,
            feels_like: 311.15,
            temp_min: 311.59,
            temp_max: 311.59,
            pressure: 999,
            sea_level: 999,
            grnd_level: 976,
            humidity: 23,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 80,
          },
          wind: {
            speed: 8.06,
            deg: 283,
            gust: 12.48,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-11 03:00:00',
        },
        {
          dt: 1718085600,
          main: {
            temp: 317.1,
            feels_like: 315.31,
            temp_min: 317.1,
            temp_max: 317.1,
            pressure: 998,
            sea_level: 998,
            grnd_level: 975,
            humidity: 13,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 71,
          },
          wind: {
            speed: 6.72,
            deg: 295,
            gust: 7.46,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-11 06:00:00',
        },
        {
          dt: 1718096400,
          main: {
            temp: 319.43,
            feels_like: 316.66,
            temp_min: 319.43,
            temp_max: 319.43,
            pressure: 995,
            sea_level: 995,
            grnd_level: 972,
            humidity: 10,
            temp_kf: 0,
          },
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          clouds: {
            all: 11,
          },
          wind: {
            speed: 5.6,
            deg: 280,
            gust: 7.33,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-11 09:00:00',
        },
        {
          dt: 1718107200,
          main: {
            temp: 318.72,
            feels_like: 316.35,
            temp_min: 318.72,
            temp_max: 318.72,
            pressure: 994,
            sea_level: 994,
            grnd_level: 971,
            humidity: 11,
            temp_kf: 0,
          },
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03d',
            },
          ],
          clouds: {
            all: 39,
          },
          wind: {
            speed: 6.72,
            deg: 276,
            gust: 7.13,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-11 12:00:00',
        },
        {
          dt: 1718118000,
          main: {
            temp: 315.82,
            feels_like: 314.48,
            temp_min: 315.82,
            temp_max: 315.82,
            pressure: 995,
            sea_level: 995,
            grnd_level: 972,
            humidity: 15,
            temp_kf: 0,
          },
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03n',
            },
          ],
          clouds: {
            all: 34,
          },
          wind: {
            speed: 6.89,
            deg: 267,
            gust: 9.56,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-11 15:00:00',
        },
        {
          dt: 1718128800,
          main: {
            temp: 313.23,
            feels_like: 312.34,
            temp_min: 313.23,
            temp_max: 313.23,
            pressure: 996,
            sea_level: 996,
            grnd_level: 973,
            humidity: 19,
            temp_kf: 0,
          },
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03n',
            },
          ],
          clouds: {
            all: 32,
          },
          wind: {
            speed: 6.68,
            deg: 274,
            gust: 12.7,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-11 18:00:00',
        },
        {
          dt: 1718139600,
          main: {
            temp: 309.91,
            feels_like: 309.72,
            temp_min: 309.91,
            temp_max: 309.91,
            pressure: 996,
            sea_level: 996,
            grnd_level: 973,
            humidity: 27,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04n',
            },
          ],
          clouds: {
            all: 62,
          },
          wind: {
            speed: 7.08,
            deg: 269,
            gust: 13.95,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'n',
          },
          dt_txt: '2024-06-11 21:00:00',
        },
        {
          dt: 1718150400,
          main: {
            temp: 308.35,
            feels_like: 308.56,
            temp_min: 308.35,
            temp_max: 308.35,
            pressure: 998,
            sea_level: 998,
            grnd_level: 974,
            humidity: 32,
            temp_kf: 0,
          },
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          clouds: {
            all: 51,
          },
          wind: {
            speed: 6.96,
            deg: 267,
            gust: 14.2,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-12 00:00:00',
        },
        {
          dt: 1718161200,
          main: {
            temp: 310.11,
            feels_like: 311.13,
            temp_min: 310.11,
            temp_max: 310.11,
            pressure: 1000,
            sea_level: 1000,
            grnd_level: 976,
            humidity: 31,
            temp_kf: 0,
          },
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03d',
            },
          ],
          clouds: {
            all: 41,
          },
          wind: {
            speed: 7.79,
            deg: 281,
            gust: 11.42,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-12 03:00:00',
        },
        {
          dt: 1718172000,
          main: {
            temp: 315.21,
            feels_like: 316.44,
            temp_min: 315.21,
            temp_max: 315.21,
            pressure: 999,
            sea_level: 999,
            grnd_level: 976,
            humidity: 22,
            temp_kf: 0,
          },
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03d',
            },
          ],
          clouds: {
            all: 30,
          },
          wind: {
            speed: 6.94,
            deg: 283,
            gust: 7.95,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-12 06:00:00',
        },
        {
          dt: 1718182800,
          main: {
            temp: 317.77,
            feels_like: 318.09,
            temp_min: 317.77,
            temp_max: 317.77,
            pressure: 996,
            sea_level: 996,
            grnd_level: 973,
            humidity: 17,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 7,
          },
          wind: {
            speed: 5.94,
            deg: 278,
            gust: 6.16,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-12 09:00:00',
        },
        {
          dt: 1718193600,
          main: {
            temp: 317.43,
            feels_like: 317.09,
            temp_min: 317.43,
            temp_max: 317.43,
            pressure: 994,
            sea_level: 994,
            grnd_level: 971,
            humidity: 16,
            temp_kf: 0,
          },
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: {
            all: 5,
          },
          wind: {
            speed: 5.95,
            deg: 279,
            gust: 6.78,
          },
          visibility: 10000,
          pop: 0,
          sys: {
            pod: 'd',
          },
          dt_txt: '2024-06-12 12:00:00',
        },
      ],
      city: {
        id: 1273294,
        name: 'Delhi',
        coord: {
          lat: 28.6517,
          lon: 77.2219,
        },
        country: 'IN',
        population: 10927986,
        timezone: 19800,
        sunrise: 1717717972,
        sunset: 1717768044,
      },
    },
    error: '',
  },
};
